### ISSUE TITLE
Add some examples

### ISSUE THREAD

**Issue by NobbZ** [exercism/haxe#1]
Add some exercises:
- [x] hello-world
- [x] bob
- [ ] word-count
- [ ] hamming
- [ ] anagram
- [ ] food-chain
- [ ] beer-song
- [ ] nucleotide-count
- [ ] rna-transcription
- [ ] phone-number
- [ ] grade-school
- [ ] robot-name
- [ ] leap
- [ ] etl
- [ ] space-age
- [ ] grains
- [ ] gigasecond
- [ ] triangle
- [ ] clock
- [ ] scrabble-score
- [ ] roman-numerals
- [ ] circular-buffer
- [ ] prime-factors
- [ ] raindrops
- [ ] allergies
- [ ] strain
- [ ] atbash-cipher
- [ ] accumulate
- [ ] crypto-square
- [ ] sieve
- [ ] simple-cipher
- [ ] luhn
- [ ] pig-latin
- [ ] pythagorean-triplet
- [ ] series
- [ ] difference-of-squares
- [ ] secret-handshake
- [ ] linked-list
- [ ] wordy
- [ ] largest-series-product
- [ ] kindergarten-garden
- [ ] binary-search-tree
- [ ] matrix
- [ ] robot-simulator
- [ ] nth-prime
- [ ] palindrome-products
- [ ] pascals-triangle
- [ ] say
- [ ] custom-set
- [ ] sum-of-multiples
- [ ] queen-attack
- [ ] saddle-points
- [ ] ocr-numbers
- [ ] meetup
- [ ] two-bucket

**Comment by kytrinyx** [comment]
Check out the "todo" field in this payload: http://x.exercism.io/tracks/haxe

**Comment by ErikSchierboom** [comment]
@Nezteb The above list contains some common exercises that are implemented among many tracks. You could use it as inspiration to pick an exercise to add. That said, the above exercises are all defined in the [problem-specifications repo](https://github.com/exercism/problem-specifications/tree/master/exercises), which contains descriptions for many exercises as well as a default set of test cases and their expected values in JSON format. With that, feel free to close this issue if you don't need it for inspiration or to keep track of the implemented exercises.

**Comment by davidbruce** [comment]
Closing this in favor of working through the [problem-specifications repo](https://github.com/exercism/problem-specifications/tree/master/exercises)
