### ISSUE TITLE
Merge exercise PRs

### ISSUE THREAD

**Issue by mfoda** [exercism/haxe#137]
@maintainers There are 57 remaining open PRs for exercises from the v2 track. Is anyone up to the task of reviewing and merging them before work starts on the v3 transition?

**Comment by davidbruce** [comment]
I'll review them over the weekend.  I'll probably be more lenient, but we do need to get these merged.  Sorry for the delay.

**Comment by iHiD** [comment]
Thanks @davidbruce!

**Comment by BNAndras** [comment]
As part of https://forum.exercism.org/t/haxe-language-track/6941, I'm doing a few cursory reviews of the remaining PRs. I don't have write access, but the ones I reviewed seem good for the most part. One or two are missing more recent tests, but they all could be reorganized to the v3 folder structure to make it easier to sync things with configlet.

**Comment by iHiD** [comment]
>  I don't have write access

Incorrect 😉

**Comment by BNAndras** [comment]
Six PRs will be ready to be merged tomorrow after some minor editing, which leaves five exercise PRs left to be reviewed.

Allergies is updated and under review by Nezteb.
Clock is updated under review by Nezteb.
Gigasecond is updated but waiting on the datetime library to be added to the CI here and to the test runner.
Grade School is being updated by me.
Meetup is being updated by me.

**Comment by BNAndras** [comment]
All exercise PRs are merged.
