### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/haxe#2]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

If you are interested in leading the charge on getting this track launched, then comment below, and I'll help get this party started based on whatever is current at the time.

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by theRemix** [comment]
i'm willing to help get this track launched.

**Comment by kytrinyx** [comment]
@theRemix That it splendid, thank you! 🌻 

I'll see if I can't scrounge up a buddy for you—someone you can ask specific questions as they come up.

**Comment by davidbruce** [comment]
This is an outdated issue and work will be done in the V2 issue.
