### ISSUE TITLE
Update ABOUT.md

### ISSUE THREAD

**Issue by BNAndras** [exercism/haxe#248]
`docs/ABOUT.md` refers to nine target languages. The subsequent table then lists eleven compiler targets with Java listed twice as both Java and JVM.

[The Haxe documentation lists active twelve compiler targets and two removed targets](https://haxe.org/documentation/introduction/compiler-targets.html). I'm proposing the table be updated to reflect the official documentation on compiler targets. Also, instead of saying target languages, we should write compiler targets.

**Comment by KirillMcQ** [comment]
I see 14 (13, including Java and not JVM) languages on the linked table, is this a mistake on my part?

**Comment by BNAndras** [comment]
Yeah, the linked table confusingly includes both active and removed targets when the preceding sentence only mentions active targets. ActionScript3 and PHP5 were removed in 2019 with Haxe 4.0. This is in line with Haxe's [Getting started with Haxe/PHP documentation](https://haxe.org/manual/target-php-getting-started.html), which says the minimum PHP version is 7.0.0 since Haxe 4.0. 

So in alphabetical order, these are the active targets.

1. C#
2. C++
3. Eval
4. Flash
5. HashLink
6. JVM
7. Java
8. JavaScript
9. Lua
10. Neko
11. PHP7
12. Python

**Comment by KirillMcQ** [comment]
Planning on updating this shortly, just wondering if I should just Google the main uses of the languages, or is there somewhere you guys got the info for that?

**Comment by BNAndras** [comment]
@ErikSchierboom, thoughts?

I feel the table takes up a lot of space to say more about the things that Haxe can compile to than about Haxe itself. I'd be inclined to remove the table and just reference that link from the beginning of the thread for current compiler targets. Then we don't need to update the table as that list changes, and it's more in line with the previous author did with linking to relevant parts of the official documentation.

**Comment by ErikSchierboom** [comment]
I agree. Removing the list and just adding a link makes a lot more sense. It might be useful to keep the goal of the `about.md` in mind: to provide students with a short and enticing introduction to the language.

**Comment by BNAndras** [comment]
@KirillMcQ, go ahead and update the ABOUT.md. If you want to tackle the next step, I'd like to trim ABOUT.md in the spirit of Erik's comment. The existing links could be moved to docs/RESOURCES.md ([example here](https://exercism.org/docs/building/tracks/docs#h-file-resources-md)).

**Comment by KirillMcQ** [comment]
Created PR of update, but denied because "We are currently in a phase of our journey where we have paused community contributions to allow us to take a breather and redesign our community model." Link: [Pull Request](https://github.com/exercism/haxe/pull/250)

**Comment by BNAndras** [comment]
Closed by #250
