### ISSUE TITLE
Is there a set of milestones needed to get the Exercism Haxe track to an active release?

### ISSUE THREAD

**Issue by Nezteb** [exercism/haxe#50]
I've been getting into Haxe recently and I love Exercism. I'd love to see an official Haxe track.

This repo has gone almost a full year with no commits/updates.

Reading through issues, I can't get a good feel for what is still remaining to be done. There are no [GitHub milestones](https://github.com/exercism/haxe/milestones) and of the 10 currently open issues, none of them are assigned to anyone. They're mostly discussion items.

I'm willing to help plan/implement whatever I can. I'm still a Haxe noob but a decent project manager and general developer.

What can we do to get this track active?

cc @kytrinyx

**Comment by iHiD** [comment]
Congrats  - you're now a Haxe Maintainer :) Thanks!

You have an invite to the Org and to manage this repo. If you email me at jeremy@exercism.io - I'll get you invited to our Slack and our other maintainers can talk you through how to get started :)

**Comment by Nezteb** [comment]
Done. ✉️ 👍
