### ISSUE TITLE
Moving from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haxe#53]
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

**Comment by davidbruce** [comment]
Hello Erik,

I have created a pull request to migrate over to GitHub Actions.  I had to update to fetch-configlet as well to get the test to pass.  Let me know if there is anything that needs fixing: https://github.com/exercism/haxe/pull/54

**Comment by ErikSchierboom** [comment]
@davidbruce Looks good to me! I've did a review.

**Comment by davidbruce** [comment]
@ErikSchierboom 

I have made the change you pointed out in the PR.

**Comment by davidbruce** [comment]
@ErikSchierboom 

This has been outstanding for a couple of days now; is there someone else that needs to approve this before merging?

**Comment by ErikSchierboom** [comment]
@davidbruce Ah no, I was waiting for you to merge :) Sorry about that. Just merged!

Closed by https://github.com/exercism/haxe/pull/54
